version: "3.3"
services:
  weatherapp_frontend:
    build: ./frontend/
    image: weatherapp_frontend:1
    ports:
      - "8000:8000"
    environment:
      - ENDPOINT=""
    volumes:
      - ./frontend/:/usr/src/weatherapp_frontend
      - /usr/src/weatherapp_frontend/node_modules/
  weatherapp_backend:
    build: ./backend/
    image: weatherapp_backend:1
    environment:
      - APPID=""
    ports:
    - "9000:9000"