version: '3.3'
services:
  frontend:
    build: ./frontend
    image: weatherapp_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/usr/src/frontend
      - /usr/src/frontend/node_modules